service: my-express-app

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    MONGO_URL: ${env:MONGO_URL}

functions:
  app:
    handler: Backend/server.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline
